const quotes = [
    ['The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius'],
    ['We suffer more often in imagination than in reality.', 'Seneca'],
    ['You have power over your mind - not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'],
    ['The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius'],
    ['Fear leads to anger. Anger leads to hate. Hate leads to suffering.', 'Yoda'],
    ['Here is a rule to remember in future, when anything tempts you to feel bitter: not "This is misfortune," but "To bear this worthily is good fortune"', 'Marcus Aurelius'],
    ['Wealth is the slave of a wise man and the master of a fool.', 'Seneca'],

    ['You always own the option of having no opinion. There is never any need to get worked up or to trouble your soul about things you can\'t control. These things are not asking to be judged by you. Leave them alone.', 'Marcus Aurelius'],
    ['True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient, for he that is so wants nothing. The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.', 'Seneca'],
    ['If a man knows not to which port he sails, no wind is favorable.', 'Seneca'],
    ['No man was ever wise by chance', 'Seneca'],
    ['A sword never kills anybody; it is a tool in the killer\'s hand.', 'Seneca'],
    ['Wealth consists not in having great possessions, but in having few wants.', 'Epictetus'],
    ['Don\'t explain your philosophy. Embody it.', 'Epictetus'],
    ['If you want to improve, be content to be thought foolish and stupid.', 'Epictetus'],
    ['It is impossible for a man to learn what he thinks he already knows.', 'Epictetus'],
    ['Circumstances don\'t make the man, they only reveal him to himself.', 'Epictetus'],
    ['No man is free who is not master of himself.', 'Epictetus'],
    ['Seek not the good in external things;seek it in yourselves.', 'Epictetus'],
    ['A gem cannot be polished without friction, nor a man perfected without trials.', 'Seneca'],
    ['The ability to simplify means to eliminate the unnecessary so that the necessary may speak.', 'Hans Hofmann'],
    ['Better than a thousand hollow words is one word that brings peace.', 'Buddha'],
    ['«La perfection est atteinte non quand il ne reste rien à ajouter, mais quand il ne reste rien à enlever». (“Perfection is attained not when there is nothing more to add, but when there is nothing more to remove”.)', 'Antoine de Saint-Exupéry'],
    ['Where wisdom reigns, there is no conflict between thinking and feeling.', 'Carl Gustav Jung'],
]
